version: "2.0"

services:
    flash:
        image: flash
        build: .
        env_file: 
            - .env
        entrypoint: sh gunicorn.sh
        ports:
             - 8000:8000

    nginx:
        image: nginx:1.17.8-alpine
        volumes:
            - /var/log/nginx/:/var/log/nginx/
            - ./docker_nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - flash
        ports:
            - 80:80
    
    # db:
    #     image: postgres:13-alpine
    #     volumes:
    #       - postgres_data:/var/lib/postgresql/data/
    #     environment:
    #       - POSTGRES_USER=hello_flask
    #       - POSTGRES_PASSWORD=hello_flask
    #       - POSTGRES_DB=hello_flask_dev

